site_name: ChunkNorris
site_url: https://wikit-ai.github.io/chunknorris/
repo_name: wikit-ai/chunknorris
repo_url: https://github.com/wikit-ai/chunknorris

theme:
  name: material
  language: en
  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  logo: assets/chunknorris_logo_1024.png # TODO : improve logo
  favicon: assets/chunknorris_logo_1024.png # TODO : improve logo
  custom_dir: docs/overrides
  features:
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - announce.dismiss
    - navigation.footer
    - navigation.tabs
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.suggest
    - toc.follow
    - toc.integrate
    - header.autohide
nav:
  - Home:
      - "ChunkNorris": index.md
      - Installation: pages/installation.md
      - Getting Started: pages/getting_started.md
      - How it works: pages/how_it_works.md
      - Performance report: pages/performance_report.md # TODO
      - Roadmap: pages/roadmap.md # -> chunknorris image
      - Current limitations: pages/current_limitations.md
      - Contributing: pages/how_to_contribute.md # TODO -> chunknorris image
      - FAQ: faq.md # TODO
  - Examples:
      - "Examples": examples/index.md # -> missing chunknorris image
      - Chunking:
          - Markdown files: examples/markdown_chunking.ipynb
          - PDF files: examples/pdf_chunking.ipynb
          - HTML files: examples/html_chunking.ipynb
          - Influence chunking behavior: examples/advanced_chunking.ipynb
      - Parsing:
          - PDF:
              - "In-depth usage of PdfParser": examples/pdf_parsing.ipynb
              - "Parsing tables": examples/example2.ipynb # TODO
      - Customize:
          - "Implement my own parser": examples/custom_parser.ipynb
          - "Implement my own pipeline": examples/example1.ipynb # TODO
  - Reference:
      - "API reference": reference/index.md
      - Chunkers: # add more
          - MarkdownChunker: reference/markdown_chunker.md
      - Parsers: # add more
          - HTMLParser: reference/html_parser.md
          - PdfParser: reference/pdf_parser.md
      - Pipelines:
          - Any Class: todo.md # TODO

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.details
  - attr_list
  - mkdocs-click
plugins:
  - search
  - mkdocs-jupyter
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          load_external_modules: false
          paths: [src]
          show_inheritance_diagramm: true
      options:
        extensions:
          - griffe_pydantic:
              schema: true
        preload_modules:
          - chunknorris

extra_css:
  - stylesheets/extra.css
extra:
  homepage: https://wikit-ai.github.io/chunknorris/
