name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.dev.txt -r requirements.txt

      - name: Black
        run: black --check --verbose ./src

      - name: Pylint
        run: pylint ./src

      - name: Mypy
        run: mypy ./src
